name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Trigger Forge Deployment
        run: |
          curl -s "${{ secrets.FORGE_DEPLOY_HOOK }}"